item_type:
  food: ['早餐', '午餐', '晚餐', '外卖', '下午茶', '火锅', '零食', '水果', '韩式料理', '日本料理', '小吃']
  shopping: ['淘宝', '京东', '衣服', '裤子', '鞋子', '手机', '电脑', '超市', '裙子', '日常用品', '包包', '美甲']
  living: ['话费', '房租', '水费', '电费', '燃气费', '网费', '培训费']
  transport: ['公车', '打车', '机票', '火车', '轮船', '公交卡', 'ofo', '摩拜']
  leisure: ['电影', '旅行', '泡吧', '聚会', '演唱会', 'KTV']
